name: sample CICD - PR
on: [push, workflow_dispatch]
jobs:
  Build:
    runs-on: self-hosted
    steps:
      - run: echo OK
  Test:
    needs: Build
    runs-on: self-hosted
    steps:
      - run: echo OK
