name: sample CICD
on: [workflow_dispatch]
jobs:
  Build:
    runs-on: self-hosted
    steps:
      - run: echo OK
  Test:
    runs-on: self-hosted
    steps:
      - run: echo OK
  Dev_Deploy:
    runs-on: self-hosted
    steps:
      - run: echo OK
  Uat_Deploy:
    runs-on: self-hosted
    steps:
      - run: echo OK
  Prod_Deploy:
    runs-on: self-hosted
    steps:
      - run: echo OK
